// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC59C6Ut-XGwHnae7SAKgESisTc8r1wbX4',
    appId: '1:32818912174:web:b56628b361ff8a39c9063f',
    messagingSenderId: '32818912174',
    projectId: 'employee-management-e7326',
    authDomain: 'employee-management-e7326.firebaseapp.com',
    storageBucket: 'employee-management-e7326.appspot.com',
    measurementId: 'G-NVDSQ58GYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz8D5OfvHvdnFd2-eSBDNcG1T3EEiaqak',
    appId: '1:32818912174:android:f5210b43fed3b8ccc9063f',
    messagingSenderId: '32818912174',
    projectId: 'employee-management-e7326',
    storageBucket: 'employee-management-e7326.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRAH5_bKV-UFRt5ETQjuhbCuWybvh7A1w',
    appId: '1:32818912174:ios:aaaf406a1dccedcec9063f',
    messagingSenderId: '32818912174',
    projectId: 'employee-management-e7326',
    storageBucket: 'employee-management-e7326.appspot.com',
    iosBundleId: 'com.sumit.employeeManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRAH5_bKV-UFRt5ETQjuhbCuWybvh7A1w',
    appId: '1:32818912174:ios:576f35438e8910ebc9063f',
    messagingSenderId: '32818912174',
    projectId: 'employee-management-e7326',
    storageBucket: 'employee-management-e7326.appspot.com',
    iosBundleId: 'com.sumit.employeeManagement.RunnerTests',
  );
}
